services:
  cve3po:
    build: .
    container_name: cve3po
    ports:
      - "8000:8000"
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: ${DEBUG}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DISABLE_REGISTER: ${DISABLE_REGISTER}
      DATABASE_PATH: ${DATABASE_PATH}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      CSRF_TRUSTED_ORIGINS: "http://localhost:8000"
    env_file:
      - .env
    volumes:
      - cve3po:/app/data
      - cve3po:/app/media

volumes:
  cve3po:
  cve3po-reports:
