# Generated by Django 5.2.12 on 2026-03-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuln_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='scan_type',
            field=models.CharField(choices=[('NMAP', 'Nmap Scan'), ('NUCLEI', 'Nuclei Scan'), ('OPENVAS', 'OpenVAS Scan')], max_length=10),
        ),
    ]
