# Generated by Django 5.2.12 on 2026-03-29 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuln_manager', '0004_vulnerability_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='vuln_manager.scan'),
        ),
    ]
