# Generated by Django 5.2.12 on 2026-03-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuln_manager', '0005_port_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='raw_file',
            field=models.FileField(blank=True, null=True, upload_to='scans/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='scan_type',
            field=models.CharField(choices=[('NMAP', 'Nmap Scan'), ('NUCLEI', 'Nuclei Scan'), ('OPENVAS', 'OpenVAS Scan'), ('MANUAL', 'Manual Entry')], max_length=10),
        ),
    ]
