# Generated by Django 5.2.12 on 2026-03-30 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuln_manager', '0007_software_vulnerability_software'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='software',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='software',
            name='listening_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vulnerabilities', to='vuln_manager.port'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='scan_type',
            field=models.CharField(choices=[('NMAP', 'Nmap Scan'), ('NUCLEI', 'Nuclei Scan'), ('OPENVAS', 'OpenVAS Scan'), ('SEMGREP', 'Semgrep SAST'), ('MANUAL', 'Manual Entry')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='software',
            unique_together={('name', 'version', 'vendor', 'listening_port')},
        ),
    ]
