# Generated by Django 5.2.12 on 2026-03-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuln_manager', '0010_vulnerability_supply_chain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='scan_type',
            field=models.CharField(choices=[('NMAP', 'Nmap Scan'), ('NUCLEI', 'Nuclei Scan'), ('OPENVAS', 'OpenVAS Scan'), ('SEMGREP', 'Semgrep SAST'), ('MANUAL', 'Manual Entry'), ('OSV', 'OSV Scan')], max_length=10),
        ),
    ]
