# Generated by Django 5.2.12 on 2026-03-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuln_manager', '0011_alter_scan_scan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='criticality',
            field=models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=15, null=True),
        ),
    ]
