# Generated by Django 5.2.12 on 2026-03-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuln_manager', '0012_host_criticality'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='criticality',
            field=models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=15, null=True),
        ),
    ]
