# Generated by Django 5.2.13 on 2026-05-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuln_manager', '0017_vulnerability_ai_last_criticality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_id', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='scan',
            name='scan_type',
            field=models.CharField(choices=[('NMAP', 'Nmap Scan'), ('NUCLEI', 'Nuclei Scan'), ('OPENVAS', 'OpenVAS Scan'), ('SEMGREP', 'Semgrep SAST'), ('MANUAL', 'Manual Entry'), ('OSV', 'OSV Scan'), ('WAZUH', 'Wazuh Live Feed')], max_length=10),
        ),
    ]
