# Generated by Django 5.2.13 on 2026-05-01 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuln_manager', '0018_extension_alter_scan_scan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='api_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='HostSoftwareRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('agent', 'Agent Collection'), ('scanner', 'Automated Scanner')], default='manual', max_length=20)),
                ('installed_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuln_manager.host')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuln_manager.software')),
            ],
            options={
                'unique_together': {('host', 'software')},
            },
        ),
    ]
