# Generated by Django 5.2.13 on 2026-05-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vuln_manager", "0019_extension_api_token_hostsoftwarerelationship"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disable_register", models.BooleanField(default=True)),
            ],
        ),
    ]
