# Generated by Django 5.2.13 on 2026-05-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vuln_manager", "0020_systemsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="wrike_folder_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vulnerability",
            name="wrike_task_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="vulnerability",
            name="wrike_task_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
