# Generated by Django 5.2.13 on 2026-05-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vuln_manager", "0022_vulnerability_dedup_and_audit"),
    ]

    operations = [
        migrations.AddField(
            model_name="host",
            name="operating_system",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
