# Generated by Django 5.2.13 on 2026-05-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vuln_manager", "0023_host_operating_system"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scan",
            name="scan_type",
            field=models.CharField(
                choices=[
                    ("NMAP", "Nmap Scan"),
                    ("NUCLEI", "Nuclei Scan"),
                    ("OPENVAS", "OpenVAS Scan"),
                    ("SEMGREP", "Semgrep SAST"),
                    ("MANUAL", "Manual Entry"),
                    ("OSV", "OSV Scan"),
                    ("NVD", "NVD Scan"),
                    ("WAZUH", "Wazuh Live Feed"),
                ],
                max_length=10,
            ),
        ),
    ]
