# Generated by Django 5.2.13 on 2026-05-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuln_manager', '0024_alter_scan_scan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='email_report_recipients',
            field=models.TextField(blank=True, null=True),
        ),
    ]
