# Generated by Django 5.2.13 on 2026-05-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vuln_manager", "0025_systemsettings_email_report_recipients"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="ai_azure_api_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="ai_azure_endpoint",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="ai_azure_model",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="ai_openrouter_api_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="ai_openrouter_model",
            field=models.CharField(default="deepseek/deepseek-v4-flash", max_length=120),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="ai_triage_provider",
            field=models.CharField(default="openrouter", max_length=20),
        ),
    ]
