# Generated by Django 5.2.13 on 2026-05-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vuln_manager", "0026_systemsettings_ai_triage_provider_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="ai_azure_api_version",
            field=models.CharField(default="2024-05-01-preview", max_length=40),
        ),
    ]
