# Generated by Django 5.2.13 on 2026-05-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vuln_manager", "0027_systemsettings_ai_azure_api_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="sla_critical_days",
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="sla_high_days",
            field=models.PositiveIntegerField(default=30),
        ),
    ]
