# Generated by Django 5.2.13 on 2026-05-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vuln_manager", "0028_systemsettings_sla_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scan",
            name="scan_type",
            field=models.CharField(
                choices=[
                    ("NMAP", "Nmap Scan"),
                    ("NUCLEI", "Nuclei Scan"),
                    ("OPENVAS", "OpenVAS Scan"),
                    ("SEMGREP", "Semgrep SAST"),
                    ("CYCLONEDX", "CycloneDX SBOM"),
                    ("MANUAL", "Manual Entry"),
                    ("OSV", "OSV Scan"),
                    ("NVD", "NVD Scan"),
                    ("WAZUH", "Wazuh Live Feed"),
                ],
                max_length=10,
            ),
        ),
    ]
