# Generated by Django 5.2.13 on 2026-06-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuln_manager', '0031_software_ai_reason_software_ai_result_cluster_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='ai_cve_system_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ai_software_system_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
