# Generated by Django 5.2.13 on 2026-06-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuln_manager', '0032_systemsettings_ai_cve_system_prompt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CisaKevEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=50, unique=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CISA KEV Entry',
                'verbose_name_plural': 'CISA KEV Entries',
            },
        ),
        migrations.CreateModel(
            name='EpssEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=50, unique=True)),
                ('score', models.FloatField()),
                ('percentile', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'EPSS Entry',
                'verbose_name_plural': 'EPSS Entries',
            },
        ),
    ]
